CREATE TABLE Asset_Types(
asset_type_ID TINYINT NOT_NULL AUTO_INCREMENT,
letter CHAR(1) NOT NULL,
name VARCHAR(20) NOT NULL,
PRIMARY KEY(asset_type_ID));

CREATE TABLE Buildings(
building_ID TINYINT NOT_NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
PRIMARY KEY(building_ID));

CREATE TABLE Rooms(
room_ID INT NOT_NULL AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
building_ID TINYINT NOT NULL,
PRIMARY KEY(room_ID),
FOREIGN KEY(building_ID) REFERENCES Buildings(building_ID));

CREATE TABLE Assets(
asset_ID INT NOT_NULL AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
asset_type_ID TINYINT NOT NULL, 
room_ID INT NOT NULL,
PRIMARY KEY(asset_ID),
FOREIGN KEY(asset_type_ID) REFERENCES Asset_Types(asset_type_ID),
FOREIGN KEY(room_ID) REFERENCES Rooms(room_ID) ON DELETE CASCADE);

CREATE TABLE Reports(
report_ID INT NOT_NULL AUTO_INCREMENT,
name VARCHAR(50),
room_ID INT NOT NULL,
create_date DATETIME NOT NULL,
PRIMARY KEY(report_ID),
FOREIGN KEY(room_ID) REFERENCES Rooms(room_ID) ON DELETE CASCADE);

--joining table between assets and reports
CREATE TABLE Reports_Assets(
report_ID NOT_NULL INT,
asset_ID NOT_NULL INT,
PRIMARY KEY(report_ID, asset_ID),
FOREIGN KEY(report_ID) REFERENCES Reports(report_ID) ON DELETE CASCADE,
FOREIGN KEY(asset_ID) REFERENCES Assets(asset_ID) ON DELETE CASCADE);

CREATE TABLE USER(
user_ID TINYINT NOT_NULL AUTO_INCREMENT,
login VARCHAR(40) NOT NULL,
salt VARCHAR(30) NOT NULL,
hash varchar(64) NOT NULL,
PRIMARY KEY(user_ID);